### ISSUE TITLE
Translate "examples" folder to tests using VisualRegressionTests.jl

### ISSUE THREAD

**Issue by Diaga** [darsnack/SpikingNN.jl#1]
@darsnack 
Hello, I would like to contribute to the repo through above project. It is my understanding that for the above project, we will have reference images stored in a separate repo and during testing, the test function will clone the repo and use those reference files for VisualRegressionTests.jl

Is this approach correct?

**Comment by darsnack** [comment]
The images don’t need to be in a separate repo. They can just be in the test folder (not yet created cause I have to set up the CI today). But your general idea is correct. The plan is to move everything in the `examples/` folder to be visual regression tests.

We will be creating the reference images by running the examples and manually inspecting them for correctness, then committing them to the test folder. One issue is that the behavior of the models are random, so we need to be able to fix the random seed on the CI so that we produce the same images.

**Comment by darsnack** [comment]
Just added the CI. [This repo](https://github.com/JuliaEarth/Variography.jl) can be a reference on using VisualRegressionTests.jl. [This issue](https://github.com/JuliaPlots/VisualRegressionTests.jl/issues/5) might also be helpful. See if you can run the examples and add the PNGs to a `test/data` folder in the repo.
