### ISSUE TITLE
Use SpikingNN.jl for LiquidStateMachine.jl?

### ISSUE THREAD

**Issue by GuillaumeLam** [darsnack/SpikingNN.jl#27]
Hello @darsnack, I stumbled across your repo recently as I am making a library to use Liquid State Machines in an RL framework. I've been using WaspNet as the snn simulator as it seemed to be the most developed library. However, the codebase you've built has more features with a more practical structure (eg. modelling the synapses). I would be very interested in re-using your work for my package rather than spend time coding & debugging to add features already implemented. (STDP, GPU support, etc.) I have been contacted by another person who is helping me rn with the LiquidStateMachine.jl repo, and I believe he would be interested is using this library too! 

I went throughout some messages and saw that it seemed that this project is on your backburner. I was therefore wondering what would need to be done to get the repo to a min state of usability? (STDP is my main feature goal, GPU acceleration would be a cherry on top!) I noticed you mentioned having a branch called kd/refactor which seems to have latest changes, but none of the examples run. :/ I did manage to run the main branch after correcting a delta call with three params. Would you recommend to use kd/refactor and read the code to know what functions to call? (I guess im wondering how usable is the branch) Would it be possible to contribute to get the repo working?

I think that SNN potential has yet to be tapped, the repo code is beautifully written imo, i hope for this repo to be an easy access for future researchers to start using SNN more in their projects without having to reimplement everything from scratch! Looking forward to hearing from you soon, Guillaume.

**Comment by GuillaumeLam** [comment]
I also had an implementation question:
What motivated not using DiffEq to solve the neuron equations? Ik that this repo dates to before CUDA.jl so perhaps DiffEq was not as mature, but [here](https://nextjournal.com/ChrisRackauckas/why-you-shouldnt-use-eulers-method-to-solve-odes#) suggests that using DiffEq could be more accurate and faster given that they now also have GPU support? Is it possible that by using DiffEq, the overhead for possibly many neurons would be too high? I am basically wondering if it would be worth solving the ODE with libs rather than an approximation. :)

**Comment by darsnack** [comment]
Hi @GuillaumeLam, thanks for your interest! You are right that the repo is not currently in a very usable state. I am in the middle of a refactor, and the primary goal is being able to use DiffEq "for free." The repo isn't on my back burner exactly; I am using it in some of my current research projects. But I have mainly focused on the models I am using in my projects...because deadlines 😅.

I expect to be pushing a complete version of my refactor in the next couple of weeks in order to make one of my research projects publicly available. The main change is that the previous interface required writing a single struct as a model for a single neuron or synapse. The package would then use StructArrays.jl to repackage an array of model structs into a struct of arrays format for performance. This ended up being difficult to support with DiffEq, and I also felt required more boilerplate than need. So now models will be "array-first," meaning that a model struct should correspond to N different parallel models.

With the refactor, the model state and parameters will be separated, and there will be a new interface `differential!` that mimics the DiffEq interface. This means that code that is compatible with this library will also be compatible DiffEq. Models that are not DEs, like SRM0, will still use the `evaluate!` interface. The high level `simulate!` function will perform fixed-time step Euler's, and a new `solve!` function (trying to think of a better name) will allow you to use DiffEq solvers instead.

----

As for why not just write everything on top of DiffEq? Since there is some interest in the package (from you and @russelljjarvis), maybe I should summarize what I think are the package goals. The main objective has been to provide an interface for easily expressing large networks of neurons. The interface should allow users to express complex architectures (similar to DNNs in Flux) and complex per neuron/synapse parameters. The interfaces should also be flexible enough to allow someone to "drop-in" their own model and expect reasonable performance.

Most importantly, you should only need to write your model/network specification once and still be able to execute on multiple backends. In my experience, there is no single simulation method/piece of hardware to rule them all. Lots of weight sparsity means you'll want to use Julia's sparse array support, temporal sparsity means you'll want an event-driven simulator, high temporal resolution or chaotic dynamics means you'll want a stiff solver, large-scale but low resolution (i.e. computational) means you want fixed time steps and low simulator overhead. For the computational side of things, I've found that when the model functions are highly optimized, using Euler's method from DiffEq is slower (more overhead) than a simple for-loop (which the fixed time step simulator is). I've also had RL + SNN projects where I needed to more fine-grained control of stepping the SNN simulation, since I needed concurrently step the RL environment and pass the RL state into the SNN. This is easy to do when `simulate!` is "just a loop," but doing the same with callbacks in DiffEq would have been too cumbersome.

**Comment by darsnack** [comment]
Also, I should mention that my current research involves reservoirs of LIF neurons as a part of the system, so I would be very interested in supporting LiquidStateMachines.jl (even if you decide to use a different library).

**Comment by GuillaumeLam** [comment]
Hey @darsnack, I want to start off by saying thank you for taking the time to explain. The refactoring in regards to the package goal you are doing makes sense, can't wait to try it out! Please lmk if there is anything I can do to help. 

That's awesome that you are using reservoirs for your research, reservoirs ftw! (there have been some very interesting papers regarding them recently) I was thinking of doing some refactoring of the repo to make it more Julia-esque. If you have any ideas or package goals/objectives that you think the repo would benefit from, please suggest away! After some thinking, I think it would be wiser to have multiple backends (waspnet, spikenn, etc.) rather than to limit to one. I am a bit unsure at the moment how to approach this requirement, I'll be able to make it work for sure but if you have a clear picture in my mind I would love to know! If you would like to contribute, just msg me and we can talk more about it!

On a future research topic, I had an idea that is being developed with a colleague. It mainly revolves around more dynamic SNN architecture with reservoirs as the basic communicating cell. Initially, brain circuits could be given to the algorithm to then perform either things like evolutionary search or pruning to find better performing circuits for a particular task or equivalently samller circuits. By having the reservoir as the basic cell, certain or all in a brain circuit could be controlled to either stop learning, have temporarily different dynamics (neuro transmitter), etc. This idea might be a bit trying to do too much at once, but what do you think? How much potential and how interesting does this seem to have to you? (I'm also thinking that this could be more of a tool to generate more future research directions) Would this idea be compatible with the repo? Would it need to be an entirely separate package?

**Comment by GuillaumeLam** [comment]
Just wanted to drop these links to packages that could speed up run time where DiffEq would be used (and just very interesting package in general imo) [Symbolics.jl](https://symbolics.juliasymbolics.org/dev/tutorials/auto_parallel/) & [DiffEqGPU.jl](https://github.com/SciML/DiffEqGPU.jl)
